## Importing the libraries

In [ ]:
#from sklearn.preprocessing import StandardScaler
#from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
#import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder

#Prepare the data

In [ ]:
data = {
    'Color': ['Red', 'Red', 'Red', 'Yellow', 'Yellow', 'Yellow', 'Yellow', 'Yellow', 'Red', 'Red'],
    'Type': ['Sport', 'Sport', 'Sport', 'Sport', 'Sport', 'SUV', 'SUV', 'SUV', 'SUV', 'Sport'],
    'Origin': ['Domestic', 'Domestic', 'Domestic', 'Domestic', 'Imported', 'Imported', 'Imported', 'Domestic', 'Imported', 'Imported'],
    'Stolen': ['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes']
}

df = pd.DataFrame(data)
df.head(10)

Color   Type    Origin Stolen
0     Red  Sport  Domestic    Yes
1     Red  Sport  Domestic     No
2     Red  Sport  Domestic    Yes
3  Yellow  Sport  Domestic     No
4  Yellow  Sport  Imported    Yes
5  Yellow    SUV  Imported     No
6  Yellow    SUV  Imported    Yes
7  Yellow    SUV  Domestic     No
8     Red    SUV  Imported     No
9     Red  Sport  Imported    Yes

#Set roles X and y for supervised-learning

In [ ]:
y_df = df[['Stolen']]
df.drop(['Stolen'], axis=1, inplace=True)
X_df = df
with pd.option_context('display.max_rows', 10): display(X_df)

Color   Type    Origin
0     Red  Sport  Domestic
1     Red  Sport  Domestic
2     Red  Sport  Domestic
3  Yellow  Sport  Domestic
4  Yellow  Sport  Imported
5  Yellow    SUV  Imported
6  Yellow    SUV  Imported
7  Yellow    SUV  Domestic
8     Red    SUV  Imported
9     Red  Sport  Imported

In [ ]:
# .values attribute is used to convert the DataFrame y_df into a NumPy array.
X = X_df.values
y = y_df.values
print(X, '\n')
print(y)

[['Red' 'Sport' 'Domestic']
 ['Red' 'Sport' 'Domestic']
 ['Red' 'Sport' 'Domestic']
 ['Yellow' 'Sport' 'Domestic']
 ['Yellow' 'Sport' 'Imported']
 ['Yellow' 'SUV' 'Imported']
 ['Yellow' 'SUV' 'Imported']
 ['Yellow' 'SUV' 'Domestic']
 ['Red' 'SUV' 'Imported']
 ['Red' 'Sport' 'Imported']] 

[['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']]


#Encoding the Independent Variables (Predictor)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), list(range(X.shape[1])))], remainder='passthrough') # list(range(X.shape[1])) can change to [0,1,2]
X = np.array(ct.fit_transform(X))
print(X)

[[1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1.]]


#Encoding the Dependent Variables (Target)

In [ ]:
from sklearn.preprocessing import LabelEncoder
y = y.ravel()  # or use y = y.reshape(-1,)
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 1 0 1 0 1 0 0 1]


#Construct model

In [ ]:
k = 3
model = KNeighborsRegressor(n_neighbors=k)
model.fit(X, y)

KNeighborsRegressor(n_neighbors=3)

#Predict unseen

In [ ]:
color_for_pred = "Red"
type_for_pred = "SUV"
origin_for_pred = "Domestic"
x_pred = [[1, 0, 1, 0, 1, 0]]
#x_pred_sc = scaler.transform(x_pred)
y_pred = model.predict(x_pred)
stolen_pred = "Yes" if y_pred[0] >= 0.5 else "No"

print('K =', k)
print(f'Color: {color_for_pred}, Type: {type_for_pred}, Origin: {origin_for_pred} => Stolen: {stolen_pred}')
print('Accuracy:', '{:.2f}'.format(model.score(X, y)))

''' Code from other colabs
k = 3
h = x_pred[0][0]
a = x_pred[0][1]
w = '{:.2f}'.format(y_pred[0])

print('K =', k)
print(f'Color: {h}, Age: {a} => Weight: {w}')
print('Accuracy:', '{:.2f}'.format(model.score(x, y)))
'''

K = 3
Color: Red, Type: SUV, Origin: Domestic => Stolen: Yes
Accuracy: 0.20


" Code from other colabs\nk = 3\nh = x_pred[0][0]\na = x_pred[0][1]\nw = '{:.2f}'.format(y_pred[0])\n\nprint('K =', k)\nprint(f'Color: {h}, Age: {a} => Weight: {w}')\nprint('Accuracy:', '{:.2f}'.format(model.score(x, y)))\n"